#pragma once

#define SW_MOUSE_BUTTON_1 0
#define SW_MOUSE_BUTTON_2 1
#define SW_MOUSE_BUTTON_3 2
#define SW_MOUSE_BUTTON_4 3
#define SW_MOUSE_BUTTON_5 4
#define SW_MOUSE_BUTTON_6 5
#define SW_MOUSE_BUTTON_7 6
#define SW_MOUSE_BUTTON_8 7

#define SW_LEFT_MOUSE_BUTTON SW_MOUSE_BUTTON_1
#define SW_RIGHT_MOUSE_BUTTON SW_MOUSE_BUTTON_2
#define SW_MIDDLE_MOUSE_BUTTON SW_MOUSE_BUTTON_3